# Sample recorder config file

# Language for emails and messages ('fr', "de" or 'us')
LANG="us"

# Prefix for audio files
PREFIX="soundbox-test"

# Server URL to access the generated MP3 files
URL_SERVER="https://server.domain.com"

# RTSP / audio source
RTSP_URL="rtsp://server.domain.com:1554/axis-media/media.amp"
RTSP_SAMPLE_RATE=16000        # in Hz
RTSP_BIT_RATE=32              # in kbits/s
RTSP_USER="<LOGIN>"
RTSP_PASSWORD="<PASSWORD>"

# Storage folders / logs
DIR_WEB="/var/www/soundbox/web"
DIR_LOG="/var/www/soundbox/logs"
DIR_PID="/var/www/soundbox"
DIR_TEMPLATE="/var/www/soundbox/recorder_templates"

# Email settings
EMAIL_FROM="<EMAIL_FROM>"
EMAIL_TO="<EMAIL_TO>"
# Email for the error message.
EMAIL_TO_SUPPORT="<EMAIL_TO_SUPPORT>"

# Audio / processing settings
INPUT_THRESHOLD=0.01          # minimum amplitude to consider as sound
MIN_VALID_SOUND_DURATION=2    # minimum valid sound duration in seconds
DURATION=900                  # recording duration in seconds

REMOVE_SILENCE=true           # remove silence
SOX_CMD="silence -l 1 0.3 -45dB -1 4.0 -45dB" # SoX command for silence removal
#SOX_GAIN=0                   # gain applied to final MP3 (0 = no gain)

KEEP_ORIGINAL=false           # keep the original WAV file in addition to MP3
